### ISSUE TITLE
Only node 18 runtime is supported currently

### ISSUE THREAD

**Issue by Xentox-Phil** [bitfocus/companion-module-template-ts#4]
I am using the developer modules path...

OS: Windows
Installed Node Version: v18.20.4
Companion Version: v3.4.2

I get the following error in the console of companion when trying to load my module:
`Instance/ModuleHost: Only node18 runtime is supported currently: "-3KZGW97MKVYgvbRbZyST"`

**Comment by krocheck** [comment]
@Xentox-Phil  I'm assuming you're trying to use node22, as the template was updated to support it.  node22 support has been added to the v3.5 betas for future release.

**Comment by Xentox-Phil** [comment]
Yes just found the commit b4f5a65 were you have upgraded it just was confused...

I just switched the runtime type back to `node18` and everything works like a charm...

thank you for your quick response absolutely awesome! ♥
